### ISSUE TITLE
Send Ton

### ISSUE THREAD

**Issue by m-a-prod** [tonkeeper/pytonapi#14]
Traceback (most recent call last):
  File "C:\Users\maprod-pc\IdeaProjects\maprod-pyramid\crypto.py", line 58, in <module>
    asyncio.run(main())
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\IdeaProjects\maprod-pyramid\crypto.py", line 33, in main
    method_result = await tonapi.blockchain.execute_get_method(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytonapi\async_tonapi\methods\blockchain.py", line 226, in execute_get_method
    response = await self._get(method=method)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytonapi\async_tonapi\client.py", line 253, in _get
    return await request("GET", method, headers, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytonapi\async_tonapi\client.py", line 196, in _request
    return await self.__process_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytonapi\async_tonapi\client.py", line 101, in __process_response
    raise error_class(error)
pytonapi.exceptions.TONAPINotFoundError: entity not found

**Comment by m-a-prod** [comment]
Я не убрал галочку что это тестнет, я дурень(((
