### ISSUE TITLE
Sending TON

### ISSUE THREAD

**Issue by fruitoiz** [tonkeeper/pytonapi#4]
Hello, how can I send a TON to another person using your library?

**Comment by nessshon** [comment]
@fruitoiz, to send TON to another person using our library pytonapi, you'll also need a library for message construction, such as tonsdk. Below is an example code you can use:

```python
import asyncio
from pytonapi import AsyncTonapi
from tonsdk.utils import bytes_to_b64str, to_nano
from tonsdk.contract.wallet import Wallets, WalletVersionEnum

# Tonapi Key
API_KEY = "AE33EX7D5...K2AO3FYQ"  # noqa

# Wallet Mnemonics
MNEMONICS = "word1 word2 word3 ..."  # noqa

# Destination Address
DESTINATION_ADDRESS = "EQC...Ness"  # noqa


async def main():
    # Initialize AsyncTonapi with the provided API key and set it to use the testnet or mainnet
    tonapi = AsyncTonapi(api_key=API_KEY, is_testnet=True)

    # Create a wallet from the provided mnemonics
    mnemonics_list = MNEMONICS.split(" ")
    _mnemonics, _pub_k, _priv_k, wallet = Wallets.from_mnemonics(
        mnemonics_list, WalletVersionEnum.v4r2, 0,
    )

    # Get the sequence number of the wallet's current state
    method_result = await tonapi.blockchain.execute_get_method(
        wallet.address.to_string(False), "seqno"
    )
    seqno = int(method_result.decoded.get("state", 0))

    # Prepare a transfer message to the destination address with the specified amount and sequence number
    transfer_amount = to_nano(float("0.1"), 'ton')
    query = wallet.create_transfer_message(
        to_addr=DESTINATION_ADDRESS,
        amount=transfer_amount,
        seqno=seqno,
    )

    # Convert the message to Base64 and send it through the Tonapi blockchain
    message_boc = bytes_to_b64str(query["message"].to_boc(False))
    data = {'boc': message_boc}
    await tonapi.blockchain.send_message(data)


if __name__ == "__main__":
    asyncio.run(main())
```

This code will send 0.1 TON to the specified address when using the correct API key and mnemonic phrase for your wallet. Please make sure you replace the placeholder values (API_KEY, MNEMONICS, DESTINATION_ADDRESS) with your actual values.

**Comment by m-a-prod** [comment]
Traceback (most recent call last):
  File "C:\Users\maprod-pc\IdeaProjects\maprod-pyramid\crypto.py", line 51, in <module>
    asyncio.run(main())
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\IdeaProjects\maprod-pyramid\crypto.py", line 31, in main
    method_result = await tonapi.blockchain.execute_get_method(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytonapi\async_tonapi\methods\blockchain.py", line 226, in execute_get_method
    response = await self._get(method=method)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytonapi\async_tonapi\client.py", line 253, in _get
    return await request("GET", method, headers, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytonapi\async_tonapi\client.py", line 196, in _request
    return await self.__process_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maprod-pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytonapi\async_tonapi\client.py", line 101, in __process_response
    raise error_class(error)
pytonapi.exceptions.TONAPINotFoundError: entity not found

I dont know what to do =(

**Comment by m-a-prod** [comment]
I forgot about testnet =(
